name: "Test"

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

jobs:
  test:
    name: "Test"
    runs-on: "ubuntu-latest"
    steps:
      - name: "Checkout the repository"
        uses: "actions/checkout@v4"

      - name: "Set up Python"
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"
          cache: "pip"

      - name: "Install requirements"
        run: python3 -m pip install -r requirements.txt

      - name: "Verify pytest-asyncio installation"
        run: python3 -c "import pytest_asyncio; print('pytest-asyncio version:', pytest_asyncio.__version__)"

      - name: "Run tests"
        run: python3 -m pytest tests/ -v --cov=pyasyncialarm --cov-report=xml --asyncio-mode=auto

      - name: "Upload coverage to Codecov"
        uses: codecov/codecov-action@v4
        with:
          file: ./coverage.xml
          flags: unittests
          name: codecov-umbrella
          fail_ci_if_error: false
